"""drop rating field from prompt model

Revision ID: 2cf10960dc01
Revises: 4a0fc27fd4ee
Create Date: 2023-09-08 23:59:03.969743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf10960dc01'
down_revision = '4a0fc27fd4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
