"""Re-add my_table with changes

Revision ID: f6282c99079e
Revises: 
Create Date: 2023-07-20 15:16:18.523752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6282c99079e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_uri', sa.String(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.prompt_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    # ### end Alembic commands ###
